"""remove original_name_slug and added custom_name

Revision ID: c9dd86c0aac9
Revises: add_oauth_tokens_table
Create Date: 2025-08-19 15:15:26.509036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9dd86c0aac9'
down_revision: Union[str, Sequence[str], None] = 'add_oauth_tokens_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_gateways_created_at'), table_name='gateways')
    op.drop_index(op.f('idx_gateways_created_by'), table_name='gateways')
    op.alter_column('oauth_tokens', 'token_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('oauth_tokens', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('oauth_tokens', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_oauth_tokens_expires'), table_name='oauth_tokens')
    op.drop_index(op.f('idx_oauth_tokens_gateway_user'), table_name='oauth_tokens')
    op.drop_constraint(op.f('unique_gateway_user'), 'oauth_tokens', type_='unique')
    op.drop_index(op.f('idx_prompts_created_at'), table_name='prompts')
    op.drop_index(op.f('idx_prompts_created_by'), table_name='prompts')
    op.drop_index(op.f('idx_resources_created_at'), table_name='resources')
    op.drop_index(op.f('idx_resources_created_by'), table_name='resources')
    op.drop_index(op.f('idx_servers_created_at'), table_name='servers')
    op.drop_index(op.f('idx_servers_created_by'), table_name='servers')
    op.drop_index(op.f('idx_tools_created_at'), table_name='tools')
    op.drop_index(op.f('idx_tools_created_by'), table_name='tools')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tools_created_by'), 'tools', ['created_by'], unique=False)
    op.create_index(op.f('idx_tools_created_at'), 'tools', ['created_at'], unique=False)
    op.create_index(op.f('idx_servers_created_by'), 'servers', ['created_by'], unique=False)
    op.create_index(op.f('idx_servers_created_at'), 'servers', ['created_at'], unique=False)
    op.create_index(op.f('idx_resources_created_by'), 'resources', ['created_by'], unique=False)
    op.create_index(op.f('idx_resources_created_at'), 'resources', ['created_at'], unique=False)
    op.create_index(op.f('idx_prompts_created_by'), 'prompts', ['created_by'], unique=False)
    op.create_index(op.f('idx_prompts_created_at'), 'prompts', ['created_at'], unique=False)
    op.create_unique_constraint(op.f('unique_gateway_user'), 'oauth_tokens', ['gateway_id', 'user_id'])
    op.create_index(op.f('idx_oauth_tokens_gateway_user'), 'oauth_tokens', ['gateway_id', 'user_id'], unique=False)
    op.create_index(op.f('idx_oauth_tokens_expires'), 'oauth_tokens', ['expires_at'], unique=False)
    op.alter_column('oauth_tokens', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('oauth_tokens', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('oauth_tokens', 'token_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('idx_gateways_created_by'), 'gateways', ['created_by'], unique=False)
    op.create_index(op.f('idx_gateways_created_at'), 'gateways', ['created_at'], unique=False)
    # ### end Alembic commands ###
